## Correlated Underlyings and Their effect on Option Payoffs

In this exercise we will analyze three types of options with different payoff structures and determine how differences in correlation between the underlying affect the payoff.

Let us consider two stocks, determined by their respective processes $\{(S_1(t), S_2(t)) : t \geq 0\}$ be geometric brownian motions with drift vector $\boldsymbol{\mu}$ and covariance matrix $\boldsymbol{\Sigma}$.

In this example, let us assume that $\boldsymbol{\mu} = [r, r]^T$ and, since all covariance matricies are real and positive semi-definite, $\boldsymbol{\Sigma}$ can be decomposed as $\boldsymbol{\Sigma} = AA^T$

If we take $A$ to be a lower triangular matrix, then this is called a Cholesky decomposition. However, I am going to do something simpler. Since this problem only involves two variables, I will set $A = \begin{pmatrix}
1 & c\\
c & 1
\end{pmatrix} $ instead of $A = \begin{pmatrix}
1 & 0\\
c & 1
\end{pmatrix} $

The second formulation is what would be used for a cholesky decomposition.

You can verify for yourself that if we take the first definition of $A$, then the variances of each process will be equal, whereas in a cholesky decomposition, that is not necessarily true.

I will choose multiple values of $c$ to control the amount of covariance that each stock has with each other.

Regarding the options, we will test three options. They and their payoffs are:

1. Spread option: $ Y_1 = \mathbb{E}^\mathbb{Q} \left[ e^{-r(T-t)}\max(S_1(T) - S_2(T) - K, 0)  | \mathcal{F}_t \right] $
2. Basket option: $ Y_1 = \mathbb{E}^\mathbb{Q} \left[ e^{-r(T-t)}\max(S_1(T) + S_2(T) - K, 0)  | \mathcal{F}_t \right] $
3. Outperformance option: $ Y_1 = \mathbb{E}^\mathbb{Q} \left[ e^{-r(T-t)}\max[\max(S_1(T) , S_2(T)) - K)]  | \mathcal{F}_t \right] $


For this example, we will choose parameters as follows

$S_1(0) = S_2(0) = 1, K = 2, r = 0.05, T = 1$
$c = -0.5, 0, 0.5$
We will use 20,000 monte carlo iterations and comment on our findings. Speaking of which, before we run any monte carlo simulations, simply by looking at the payoffs, we expect that when $S_1$ and $S_2$ diverge significantly, we expect a high payoff on the spread and a low payoff on the basket. Thus, when we believe stocks are negatively correlated, we prefer the spread option. Similarly, we expect that when $S_1$ and $S_2$ are highly correlated, we expect a high payoff on the basket and a low payoff on the spread. Thus, when we believe stocks are positively correlated, we prefer the basket option.

In [4]:
import numpy as np
import scipy.stats as sp
import matplotlib.pyplot as plt

# GBM parameters
r = 0.05
mu = np.array([r, r])
S0_1 = 1
S0_2 = 1

# Other parameters
K = 2; # strike

c_values = [-0.5, 0, 0.5]
Sigma_values = [0 , 0, 0]

for i in range(len(c_values)):
    c = c_values[i]
    A = np.array([[1,c],[c,1]])
    print(A)
    Sigma_values[i] = np.matmul(A, np.transpose(A))

print(Sigma_values)


[[ 1.  -0.5]
 [-0.5  1. ]]
[[1 0]
 [0 1]]
[[1.  0.5]
 [0.5 1. ]]
[array([[ 1.25, -1.  ],
       [-1.  ,  1.25]]), array([[1, 0],
       [0, 1]]), array([[1.25, 1.  ],
       [1.  , 1.25]])]
